### ISSUE TITLE
Reverse question

### ISSUE THREAD

**Issue by kodxana** [go-compile/localrelay#2]
Would this tool work in reverse if I have tor hidden service I would want to expose on clearness?

**Comment by go-compile** [comment]
Hi Kodxana,

Yes! This is similar to how I use Localrelay to access my home lab when I'm away from home.

By the sounds of things, you want to expose the hidden service to the internet, for this you will need to host Localrelay on a VPS with an open port or use a third party proxying service like Ngrok to communicate to Localrelay with Localrelay then communicating through Tor; although I'm looking into implementing Ngrok like functionality in the future.

If you need help setting this up please let me know and I'll be happy to help!

**Comment by kodxana** [comment]
Nah I'm looking at solution like this.

clearnet - proxy - onion - app

Kinda want my help expose my friends app that is only accessible over onion as limitation on my friends side.

**Comment by go-compile** [comment]
That sounds completely doable.

All you would need to do is setup your relay to listen on whatever port you wish and make it bind to all interfaces e.g. 0.0.0.0:80, then setup your destination to be the onion address and port and then configure the SOCKS5 proxy to use Tor, so socks5://127.0.0.1:9050.

That will take traffic from the clearnet then send it to the onion using the Tor socks5 proxy which then sends the traffic to the application behind the onion.

**Comment by kodxana** [comment]
In my case all worked fine except of loading website css and images as it was most time reported as corupted.
Kinda not sure how to fix it.

Link: ttauyzmy4kbm5yxpujpnahy7uxwnb32hh3dja7uda64vefpkomf3s4yd.onion
Page is safe to work just in case.

**Comment by go-compile** [comment]
May I ask what relay type you are using? If you're using a http relay, try a TCP relay, as a TCP relay is best equipped for this use case.

I've also tried on my machine but it appears the onion is offline.
